<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>9e5206b9-9a08-4339-b59b-ef49943bd43a</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Airnb.Domain\Airnb.Domain.csproj" />
    <ProjectReference Include="..\Airnb.Shared\Airnb.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Usecases\Hosts\UpdateHost\" />
  </ItemGroup>

</Project>
